### ISSUE TITLE
error when selecting 2017 versions

### ISSUE THREAD

**Issue by LifeCANvs** [deepak-rathi/VS2017OfflineSetupUtility#19]
Hi. I am trying to download the VS 2017 Community Edition offline install files and after many attempts with the official MS installer (via the command line --layout options) and trying various other download sources without success, I finally found this GH project of yours. I just downloaded and opened your program, but if I select Visual Studio 2017 CE or any of the other 2017 editions, it only shows an error popup box, telling me to make sure the Internet is connected... If I however select any of the 2019 or 2022 editions, the list of downloadable components is refreshed and no error is displayed.

So is this it... did M$ "do it again" again... making yet another one of their better tools completely unavailable for use anymore by removing the downloads for it, or can you think of a way to resolve this problem and still get VS 2017 CE downloaded for offline install?

![2024-11-08_165009 error when selecting 2017CE](https://github.com/user-attachments/assets/34bd0bc0-9085-4689-bd90-1656f52b8340)

**Comment by deepak-rathi** [comment]
@LifeCANvs This repo depends on the official repo "https://github.com/MicrosoftDocs/visualstudio-docs/tree/main/docs/install/includes/" for up to date values of workload and packages. 

But if you see the commit "https://github.com/MicrosoftDocs/visualstudio-docs/commit/e33f6d13310130c5f90ee85967e85a6b3a86dee0" the folder with "vs-2017" is no longer available but other version folder still exist.

That's why you are getting this ERROR message and application is unable to load "https://raw.githubusercontent.com/MicrosoftDocs/visualstudio-docs/master/docs/install/includes/vs-2017/workload-component-id-vs-community.md"

You can still download the Official installer from "https://aka.ms/vs/15/release/vs_community.exe"

**Comment by deepak-rathi** [comment]
You can build the command using other version and manually execute it for the "https://aka.ms/vs/15/release/vs_community.exe"

**Comment by deepak-rathi** [comment]
I will release a new build with the fix.

**Comment by deepak-rathi** [comment]
Fixed and new version 1.4.4 released

**Comment by LifeCANvs** [comment]
> Fixed and new version 1.4.4 released

Thank you SO MUCH! This new version eventually worked, and I now have the offline layout for VS2017CE that I wanted.

I will open another issue to explain the problems that occurred and how I worked around that to make it work...
